// One-off generator: parses the Rotom .ino bitmap arrays and emits
// src/data/rotomSprites.js. Re-run with `node scripts/genRotomSprites.js` if the
// sketch's sprites change. Not part of the app build.
const fs = require("fs");
const path = require("path");

const ino = fs.readFileSync(path.join(__dirname, "../src/Assets/rotom.ino"), "utf8");

// name -> byte array, for every `const unsigned char <name> [] PROGMEM = { ... };`
const re = /const unsigned char (epd_bitmap_\w+)\s*\[\]\s*PROGMEM\s*=\s*\{([^}]*)\}/g;
const sprites = {};
let m;
while ((m = re.exec(ino)) !== null) {
  const bytes = m[2].match(/0x[0-9a-fA-F]{2}/g).map((h) => parseInt(h, 16));
  if (bytes.length !== 1024) throw new Error(`${m[1]} has ${bytes.length} bytes, expected 1024`);
  sprites[m[1]] = bytes;
}

// Only the frames the on-page animation needs.
const want = {
  IDLE1: "epd_bitmap_RotomSprite1",
  IDLE2: "epd_bitmap_RotomSprite2",
  NEUTRAL3: "epd_bitmap_RotomNeutral3",
  BANANA3: "epd_bitmap_RotomSprite3Banana__1_",
  BANANA4: "epd_bitmap_RotomSprite4Banana__1_",
  CHERI3: "epd_bitmap_RotomSprite3Cheri__1_",
  CHERI4: "epd_bitmap_RotomSprite4Cheri__1_",
  LEPPA3: "epd_bitmap_RotomSprite3LeppaTest",
  LEPPA4: "epd_bitmap_RotomSprite4Leppa__1_",
};

const fmt = (arr) => {
  const rows = [];
  for (let i = 0; i < arr.length; i += 16) {
    rows.push("  " + arr.slice(i, i + 16).map((b) => "0x" + b.toString(16).padStart(2, "0")).join(","));
  }
  return "[\n" + rows.join(",\n") + ",\n]";
};

let out = `// AUTO-GENERATED by scripts/genRotomSprites.js from src/Assets/rotom.ino.
// Do not edit by hand. Each sprite is 128x64px, 1bpp, MSB-first (Adafruit
// drawBitmap format). Edit the .ino and re-run the generator instead.

export const SCREEN_W = 128;
export const SCREEN_H = 64;

`;
for (const [key, name] of Object.entries(want)) {
  if (!sprites[name]) throw new Error(`missing ${name} in rotom.ino`);
  out += `export const ${key} = ${fmt(sprites[name])};\n\n`;
}

// Fruit feed pairs (sprite3 = mouth open, sprite4 = mouth closed) + idle frames.
out += `export const FRUITS = [ [BANANA3, BANANA4], [CHERI3, CHERI4], [LEPPA3, LEPPA4] ];\n`;
out += `export const rotomFrames = [IDLE2, IDLE1];\n`;

fs.writeFileSync(path.join(__dirname, "../src/data/rotomSprites.js"), out);
console.log("wrote src/data/rotomSprites.js with sprites:", Object.keys(want).join(", "));
